name: codecv6
recipe: laravel
config:
  php: '8.3'
  webroot: public
  via: nginx
  database: mysql:8.0
  xdebug: true
  config:
    php: php.ini

services:
  appserver:
    type: php:8.3
    build_as_root:
      - apt-get update && apt-get install -y --no-install-recommends libpng-dev libjpeg-dev libfreetype6-dev
      - docker-php-ext-configure gd --with-freetype --with-jpeg
      - docker-php-ext-install -j$(nproc) gd pdo pdo_mysql
    overrides:
      environment:
        PHP_MEMORY_LIMIT: -1
        UPLOAD_MAX_FILESIZE: 100M
        POST_MAX_SIZE: 100M
