#!/bin/bash

#ddev-generated
# Support for TablePlus, https://tableplus.com/
# This command is available if macOS and TablePlus is installed in the normal place
## Description: Run tableplus with current project database
## Usage: tableplus
## Example: "ddev tableplus"
## OSTypes: darwin
## HostBinaryExists: /Applications/TablePlus.app

url=${DOCKER_HOST##*tcp://}
url=${url%%:*}
dbtype=${DDEV_DBIMAGE%:*}
driver=mysql
if [[ $dbtype == "postgres" ]]; then
    driver=$dbtype
fi
query="${driver}://db:db@${url}:${DDEV_HOST_DB_PORT}/db"

set -x
open "$query" -a "/Applications/TablePlus.app/Contents/MacOS/TablePlus"
